apiVersion: v1
kind: ResourceQuota
metadata:
  name: large-cpu-memory-quota
spec:
  hard:
    requests.cpu: 1500m
    requests.memory: 5Gi
    limits.cpu: '6'
    limits.memory: 6Gi
  scopes:
    - NotTerminating