{{- range untilStep 1 (int .Values.Users) 1 }}
{{ $n := . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-gitops-argocd-application-controller_edit_role
  namespace: user{{$n}}-openshift-gitops
roleRef:
  name: edit
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  # apiGroup: "rbac.authorization.k8s.io"
  namespace: openshift-gitops
{{- end }}