{{- range untilStep 1 (int .Values.Users) 1 }}
{{ $n := . }}
---
kind: Namespace
apiVersion: v1
metadata:
  annotations:
    openshift.io/requester: user{{$n}}
  name: user{{$n}}-openshift-gitops
---
kind: Namespace
apiVersion: v1
metadata:
  annotations:
    openshift.io/requester: user{{$n}}
  name: user{{$n}}-petclinic
{{- end }}