{{- range untilStep 1 (int .Values.Users) 1 }}
{{ $n := . }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user{{$n}}-admin-user{{$n}}-namespace
  namespace: user{{$n}}
  labels:
    app: workshop-gitops
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user{{$n}}
    namespace: user{{$n}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
{{- end }}