apiVersion: v1
kind: ResourceQuota
metadata:
  name: small-cpu-memory-quota
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 1Gi
    limits.cpu: '1'
    limits.memory: 2Gi
  scopes:
    - NotTerminating